// <auto-generated />
using System;
using Aegis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aegis.Data.Migrations
{
    [DbContext(typeof(AegisDbContext))]
    partial class AegisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aegis.Data.AccessLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ActorEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ActorUid")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ExtraJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TargetId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TargetKind")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("Ts")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Ua")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("Ts");

                    b.HasIndex("Action", "Ts");

                    b.ToTable("AccessLog", (string)null);
                });

            modelBuilder.Entity("Aegis.Data.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedByUid")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Announcement", (string)null);
                });

            modelBuilder.Entity("Aegis.Data.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("FailedLogins")
                        .HasColumnType("int");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LockoutUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LoginId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("StaffId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("LoginId")
                        .IsUnique();

                    b.HasIndex("StaffId");

                    b.ToTable("AppUser", (string)null);
                });

            modelBuilder.Entity("Aegis.Data.ArchiveReport", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("BackedUpAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Csv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CsvSavedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Year", "Month");

                    b.ToTable("ArchiveReport", (string)null);
                });

            modelBuilder.Entity("Aegis.Data.ExStaff", b =>
                {
                    b.Property<string>("StaffId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarThumb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedByEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeletedByUid")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("HadAvatar")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TenureYears")
                        .HasColumnType("int");

                    b.HasKey("StaffId");

                    b.ToTable("ExStaff", (string)null);
                });

            modelBuilder.Entity("Aegis.Data.LeaveWishDay", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("StaffId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.HasKey("Year", "Month", "StaffId", "Day");

                    b.ToTable("LeaveWishDay", (string)null);
                });

            modelBuilder.Entity("Aegis.Data.LeaveWishEntry", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("StaffId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("FirstSubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Year", "Month", "StaffId");

                    b.ToTable("LeaveWishEntry", (string)null);
                });

            modelBuilder.Entity("Aegis.Data.LeaveWishWindow", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DaysPerPerson")
                        .HasColumnType("int");

                    b.Property<bool>("Open")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("OpenedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Quota")
                        .HasColumnType("int");

                    b.Property<int>("ReqD")
                        .HasColumnType("int");

                    b.Property<int>("ReqE")
                        .HasColumnType("int");

                    b.Property<int>("ReqN")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Year", "Month");

                    b.ToTable("LeaveWishWindow", (string)null);
                });

            modelBuilder.Entity("Aegis.Data.LegacyHashConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("MemoryCost")
                        .HasColumnType("int");

                    b.Property<int>("Rounds")
                        .HasColumnType("int");

                    b.Property<string>("SaltSeparator")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SignerKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("LegacyHashConfig", (string)null);
                });

            modelBuilder.Entity("Aegis.Data.LevelBonus", b =>
                {
                    b.Property<string>("Level")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("Level");

                    b.ToTable("LevelBonus", (string)null);
                });

            modelBuilder.Entity("Aegis.Data.MonthlyHealthStat", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Avg")
                        .HasColumnType("int");

                    b.Property<int>("Median")
                        .HasColumnType("int");

                    b.HasKey("Year", "Month");

                    b.ToTable("MonthlyHealthStat", (string)null);
                });

            modelBuilder.Entity("Aegis.Data.OneTimeToken", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("TokenHash");

                    b.HasIndex("UserId", "Purpose");

                    b.ToTable("OneTimeToken", (string)null);
                });

            modelBuilder.Entity("Aegis.Data.PasswordHistoryEntry", b =>
                {
                    b.Property<string>("StaffId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Seq")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("StaffId", "Seq");

                    b.ToTable("PasswordHistory", (string)null);
                });

            modelBuilder.Entity("Aegis.Data.RefreshToken", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FamilyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Persistent")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("TokenHash");

                    b.HasIndex("FamilyId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("Aegis.Data.ScheduleCell", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<byte>("Kind")
                        .HasColumnType("tinyint");

                    b.Property<string>("RowKey")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<string>("ShiftTime")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Year", "Month", "Kind", "RowKey", "Day");

                    b.ToTable("ScheduleCell", (string)null);
                });

            modelBuilder.Entity("Aegis.Data.ScheduleMonth", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Year", "Month");

                    b.ToTable("ScheduleMonth", (string)null);
                });

            modelBuilder.Entity("Aegis.Data.SchedulePublicView", b =>
                {
                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("RowKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShiftTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vSchedulePublic", (string)null);
                });

            modelBuilder.Entity("Aegis.Data.SettlementRecord", b =>
                {
                    b.Property<string>("StaffId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Period")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int>("Annual")
                        .HasColumnType("int");

                    b.Property<int>("Night")
                        .HasColumnType("int");

                    b.Property<int>("Ot")
                        .HasColumnType("int");

                    b.HasKey("StaffId", "Period");

                    b.ToTable("SettlementRecord", (string)null);
                });

            modelBuilder.Entity("Aegis.Data.ShiftOption", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Code");

                    b.ToTable("ShiftOption", (string)null);
                });

            modelBuilder.Entity("Aegis.Data.Staff", b =>
                {
                    b.Property<string>("StaffId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("AccumulatedOt")
                        .HasColumnType("int");

                    b.Property<int?>("AnnualLeaveUsed")
                        .HasColumnType("int");

                    b.Property<bool>("CanNightShift")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLeader")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPregnantOrNursing")
                        .HasColumnType("bit");

                    b.Property<string>("LeaveStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NightShiftBalance")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PdpaConsentedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PdpaNoticeVersion")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool?>("ProfileCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ProfileCompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProfileUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SpecialStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("TenureYears")
                        .HasColumnType("int");

                    b.HasKey("StaffId");

                    b.ToTable("Staff", (string)null);
                });

            modelBuilder.Entity("Aegis.Data.StaffAvatar", b =>
                {
                    b.Property<string>("StaffId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarThumb")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffId");

                    b.ToTable("StaffAvatar", (string)null);
                });

            modelBuilder.Entity("Aegis.Data.StaffPublicView", b =>
                {
                    b.Property<string>("AvatarThumb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLeader")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vStaffPublic", (string)null);
                });

            modelBuilder.Entity("Aegis.Data.StaffSensitive", b =>
                {
                    b.Property<string>("StaffId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("StaffId");

                    b.ToTable("StaffSensitive", (string)null);
                });

            modelBuilder.Entity("Aegis.Data.WardSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("BedCount")
                        .HasColumnType("int");

                    b.Property<string>("HospitalLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("OptimalD")
                        .HasColumnType("int");

                    b.Property<int?>("OptimalE")
                        .HasColumnType("int");

                    b.Property<int?>("OptimalN")
                        .HasColumnType("int");

                    b.Property<int?>("PublishedMonth")
                        .HasColumnType("int");

                    b.Property<int?>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<int>("RatioD")
                        .HasColumnType("int");

                    b.Property<int>("RatioE")
                        .HasColumnType("int");

                    b.Property<int>("RatioN")
                        .HasColumnType("int");

                    b.Property<int>("ReqD")
                        .HasColumnType("int");

                    b.Property<int>("ReqE")
                        .HasColumnType("int");

                    b.Property<int>("ReqN")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WardSettings", (string)null);
                });

            modelBuilder.Entity("Aegis.Data.LeaveWishDay", b =>
                {
                    b.HasOne("Aegis.Data.LeaveWishEntry", null)
                        .WithMany("Days")
                        .HasForeignKey("Year", "Month", "StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aegis.Data.SettlementRecord", b =>
                {
                    b.HasOne("Aegis.Data.Staff", null)
                        .WithMany("Settlements")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aegis.Data.StaffAvatar", b =>
                {
                    b.HasOne("Aegis.Data.Staff", null)
                        .WithOne("Avatar")
                        .HasForeignKey("Aegis.Data.StaffAvatar", "StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aegis.Data.StaffSensitive", b =>
                {
                    b.HasOne("Aegis.Data.Staff", null)
                        .WithOne("Sensitive")
                        .HasForeignKey("Aegis.Data.StaffSensitive", "StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Aegis.Security.EncryptedValue", "BankAccount", b1 =>
                        {
                            b1.Property<string>("StaffSensitiveStaffId")
                                .HasColumnType("nvarchar(32)");

                            b1.Property<byte[]>("Ciphertext")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasColumnName("BankAccountCiphertext");

                            b1.Property<string>("KeyId")
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)")
                                .HasColumnName("BankAccountKeyId");

                            b1.Property<byte[]>("Nonce")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("varbinary(12)")
                                .HasColumnName("BankAccountNonce");

                            b1.Property<byte[]>("Tag")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("varbinary(16)")
                                .HasColumnName("BankAccountTag");

                            b1.Property<byte>("Version")
                                .HasColumnType("tinyint")
                                .HasColumnName("BankAccountVersion");

                            b1.HasKey("StaffSensitiveStaffId");

                            b1.ToTable("StaffSensitive");

                            b1.WithOwner()
                                .HasForeignKey("StaffSensitiveStaffId");
                        });

                    b.OwnsOne("Aegis.Security.EncryptedValue", "IdNumber", b1 =>
                        {
                            b1.Property<string>("StaffSensitiveStaffId")
                                .HasColumnType("nvarchar(32)");

                            b1.Property<byte[]>("Ciphertext")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasColumnName("IdNumberCiphertext");

                            b1.Property<string>("KeyId")
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)")
                                .HasColumnName("IdNumberKeyId");

                            b1.Property<byte[]>("Nonce")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("varbinary(12)")
                                .HasColumnName("IdNumberNonce");

                            b1.Property<byte[]>("Tag")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("varbinary(16)")
                                .HasColumnName("IdNumberTag");

                            b1.Property<byte>("Version")
                                .HasColumnType("tinyint")
                                .HasColumnName("IdNumberVersion");

                            b1.HasKey("StaffSensitiveStaffId");

                            b1.ToTable("StaffSensitive");

                            b1.WithOwner()
                                .HasForeignKey("StaffSensitiveStaffId");
                        });

                    b.OwnsOne("Aegis.Security.EncryptedValue", "Phone", b1 =>
                        {
                            b1.Property<string>("StaffSensitiveStaffId")
                                .HasColumnType("nvarchar(32)");

                            b1.Property<byte[]>("Ciphertext")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasColumnName("PhoneCiphertext");

                            b1.Property<string>("KeyId")
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)")
                                .HasColumnName("PhoneKeyId");

                            b1.Property<byte[]>("Nonce")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("varbinary(12)")
                                .HasColumnName("PhoneNonce");

                            b1.Property<byte[]>("Tag")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("varbinary(16)")
                                .HasColumnName("PhoneTag");

                            b1.Property<byte>("Version")
                                .HasColumnType("tinyint")
                                .HasColumnName("PhoneVersion");

                            b1.HasKey("StaffSensitiveStaffId");

                            b1.ToTable("StaffSensitive");

                            b1.WithOwner()
                                .HasForeignKey("StaffSensitiveStaffId");
                        });

                    b.Navigation("BankAccount");

                    b.Navigation("IdNumber");

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("Aegis.Data.WardSettings", b =>
                {
                    b.OwnsOne("Aegis.Security.EncryptedValue", "BaseSalary", b1 =>
                        {
                            b1.Property<int>("WardSettingsId")
                                .HasColumnType("int");

                            b1.Property<byte[]>("Ciphertext")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasColumnName("BaseSalaryCiphertext");

                            b1.Property<string>("KeyId")
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)")
                                .HasColumnName("BaseSalaryKeyId");

                            b1.Property<byte[]>("Nonce")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("varbinary(12)")
                                .HasColumnName("BaseSalaryNonce");

                            b1.Property<byte[]>("Tag")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("varbinary(16)")
                                .HasColumnName("BaseSalaryTag");

                            b1.Property<byte>("Version")
                                .HasColumnType("tinyint")
                                .HasColumnName("BaseSalaryVersion");

                            b1.HasKey("WardSettingsId");

                            b1.ToTable("WardSettings");

                            b1.WithOwner()
                                .HasForeignKey("WardSettingsId");
                        });

                    b.Navigation("BaseSalary");
                });

            modelBuilder.Entity("Aegis.Data.LeaveWishEntry", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("Aegis.Data.Staff", b =>
                {
                    b.Navigation("Avatar");

                    b.Navigation("Sensitive");

                    b.Navigation("Settlements");
                });
#pragma warning restore 612, 618
        }
    }
}
