<?php

namespace App\Http\Controllers;

use App\Support\Csrf;
use App\Support\Firebase;
use Google\Cloud\Firestore\FieldValue;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

/**
 * 月底自動結算 — 對應 api/auto-settle.js
 *
 * POST /api/auto-settle
 *   query string 控制：
 *     ?healthCheck=true   → 純健康檢查（會打一次 Firestore）
 *     ?force=true         → 略過「明天是 1 號」的時間檢查，強制執行
 *     ?targetDate=YYYY-MM-DD → Time Tuner：拿這天當「今天」，方便回放歷史月份
 *
 * 流程：
 *   1. CSRF + 雙軌 auth：token === CRON_SECRET（cron 觸發）OR admin Firebase token
 *   2. 時間檢查：tomorrow.getDate() === 1（即今天是月底）才執行；非月底直接 skip
 *   3. 讀 NurseApp/Staff + Schedules/{year-month}（連字號）
 *   4. 產 CSV（含 UTF-8 BOM）—— 沿用 JS 端目前的 placeholder CSV 格式
 *   5. 寫 archive_reports/{year_month}（底線）含 server timestamp + autoGenerated 旗標
 *
 * 注意：JS 版的 healthCheck / force / targetDate 都讀 query string；PHP 端維持一致以便
 * Vercel Cron / 任何排程工具能直接打同樣的 URL 而不需改參數位置。
 */
class AutoSettleController extends Controller
{
    public function handle(Request $request): JsonResponse
    {
        // healthCheck（query string，CSRF/auth 之前放行）
        if ($request->query('healthCheck') === 'true') {
            try {
                Firebase::firestore()->document('NurseApp/Settings')->snapshot();
                return response()->json(['ok' => true, 'service' => 'auto-settle']);
            } catch (\Throwable $err) {
                return response()->json([
                    'ok' => false, 'service' => 'auto-settle', 'error' => $err->getMessage(),
                ], 503);
            }
        }

        // CSRF（Csrf::check 已允許「無 Origin + 帶 CRON_SECRET」的 cron 路徑）
        if (!Csrf::check($request)) {
            return response()->json(['error' => '禁止：非法來源'], 403);
        }

        // —— 雙軌 auth：CRON_SECRET 或 admin Firebase token ——
        $authHeader = (string) $request->header('authorization');
        if (!str_starts_with($authHeader, 'Bearer ')) {
            return response()->json(['error' => '未經授權：缺少登入憑證'], 401);
        }
        $token      = substr($authHeader, 7);
        $cronSecret = env('CRON_SECRET');
        $isCronCall = (is_string($cronSecret) && $cronSecret !== '' && hash_equals($cronSecret, $token));

        if (!$isCronCall) {
            try {
                $verified = Firebase::auth()->verifyIdToken($token);
                $email    = (string) ($verified->claims()->get('email') ?? '');
                if ($email !== 'admin@hospital.com') {
                    return response()->json(['error' => '權限不足：只有管理員能執行此操作'], 403);
                }
            } catch (\Throwable $e) {
                logger()->warning('攔截到未經授權的結算請求: ' . $e->getMessage());
                return response()->json(['error' => '未經授權：登入憑證無效或已過期'], 401);
            }
        }

        try {
            // ── Time Tuner ──
            $isForceRun    = ($request->query('force') === 'true');
            $targetDateStr = $request->query('targetDate');

            $tz = new \DateTimeZone('UTC');  // 與 JS new Date() server-side(UTC)行為一致
            if (is_string($targetDateStr) && $targetDateStr !== '') {
                try {
                    $today = new \DateTimeImmutable($targetDateStr, $tz);
                } catch (\Exception $e) {
                    return response()->json(['error' => 'targetDate 格式錯誤，請用 YYYY-MM-DD'], 400);
                }
            } else {
                $today = new \DateTimeImmutable('now', $tz);
            }

            $tomorrow = $today->modify('+1 day');
            // 非月底 + 沒帶 force → 跳過（與 JS 版同樣靜默回 200，避免 cron 噪音）
            if (!$isForceRun && (int) $tomorrow->format('j') !== 1) {
                return response()->json(['message' => '尚未到月底最後一天，跳過自動結算。']);
            }

            $year  = (int) $today->format('Y');
            $month = (int) $today->format('n');

            $scheduleDocId = "{$year}-{$month}";   // Schedules 用連字號
            $archiveDocId  = "{$year}_{$month}";   // archive_reports 用底線

            $firestore   = Firebase::firestore();
            $staffRef    = $firestore->document('NurseApp/Staff');
            $scheduleRef = $firestore->document("Schedules/{$scheduleDocId}");

            // 兩個 doc 都讀（JS 用 Promise.all，PHP 同步序列即可，Firestore REST 每次 ~200ms）
            $staffSnap    = $staffRef->snapshot();
            $scheduleSnap = $scheduleRef->snapshot();

            if (!$scheduleSnap->exists()) {
                return response()->json([
                    'error' => "❌ 找不到 {$year}年{$month}月 的班表，無法結算！(尋找的文檔ID: {$scheduleDocId})",
                ], 404);
            }

            $staffData = $staffSnap->exists() && is_array($staffSnap->data()['staffData'] ?? null)
                ? $staffSnap->data()['staffData']
                : [];
            $finalized = is_array($scheduleSnap->data()['finalizedSchedule'] ?? null)
                ? $scheduleSnap->data()['finalizedSchedule']
                : [];

            $baseSalary = 40000;

            // —— CSV 產生（沿用 JS 版目前的 placeholder 格式 + BOM）——
            // JS 版 CSV 是粗略草稿（日格欄位是 ... 字面值），這裡 1:1 對齊以保資料形狀。
            // 之後要把 CSV 升級為完整 31 天欄位 + 健康度真值時，兩邊同步即可。
            $csv = "\xEF\xBB\xBF" . "工號,姓名,1號...[略],健康度,總工時,加班費,預估總薪資\n";

            foreach ($finalized as $staffId => $schedule) {
                // 虛擬空缺（D 開頭）不算薪
                if (str_starts_with((string) $staffId, 'D')) {
                    continue;
                }
                // 從 staffData 找名字
                $name = '未知';
                foreach ($staffData as $s) {
                    if (($s['staff_id'] ?? null) === $staffId) {
                        $name = $s['name'] ?? '未知';
                        break;
                    }
                }

                $workDays   = 0;
                $nightCount = 0;
                if (is_array($schedule)) {
                    foreach ($schedule as $cell) {
                        $type = is_array($cell) ? ($cell['type'] ?? null) : $cell;
                        if (in_array($type, ['D', 'E', 'N', '支援'], true)) {
                            $workDays++;
                        }
                        if ($type === 'N') {
                            $nightCount++;
                        }
                    }
                }

                $totalSalary = $baseSalary + ($nightCount * 500);
                $csv .= "{$staffId},{$name},...,90,{$workDays},0,{$totalSalary}\n";
            }

            // 寫入歷史庫
            $firestore->document("archive_reports/{$archiveDocId}")->set([
                'csv'           => $csv,
                'timestamp'     => FieldValue::serverTimestamp(),
                'autoGenerated' => true,
            ]);

            return response()->json([
                'success' => true,
                'message' => "✅ [TimeTuner: {$year}-{$month}] 自動結算上傳成功！",
            ]);
        } catch (\Throwable $err) {
            logger()->error('auto-settle 失敗: ' . $err->getMessage());
            return response()->json(['error' => '伺服器執行時發生錯誤'], 500);
        }
    }
}
