// api/auto-settle.js 頂部
import admin from 'firebase-admin';

if (!admin.apps.length) {
  admin.initializeApp({
    credential: admin.credential.cert({
      projectId: process.env.FIREBASE_PROJECT_ID,
      clientEmail: process.env.FIREBASE_CLIENT_EMAIL,
      // 關鍵：將環境變數中的 \n 轉回真正的換行符號
      privateKey: process.env.FIREBASE_PRIVATE_KEY?.replace(/\\n/g, '\n'),
    }),
  });
}
const db = admin.firestore();

export default async function handler(req, res) {
  // 檢查是否為月底最後一天
  const today = new Date();
  const tomorrow = new Date(today);
  tomorrow.setDate(today.getDate() + 1);
  if (tomorrow.getDate() !== 1) {
    return res.status(200).json({ message: '尚未到月底，跳過自動結算。' });
  }

  const year = today.getFullYear();
  const month = today.getMonth() + 1;
  const docId = `${year}_${month}`;

  try {
    console.log(`正在執行 ${docId} 自動結算任務...`);

    // 2. 從 Firestore 抓取資料
    const [staffSnap, scheduleSnap] = await Promise.all([
      db.collection('NurseApp').doc('Staff').get(),
      db.collection('Schedules').doc(docId).get()
    ]);

    if (!scheduleSnap.exists) throw new Error("找不到當月發布班表");
    
    const staffData = staffSnap.data()?.staffData || [];
    const finalizedSchedule = scheduleSnap.data()?.finalizedSchedule || {};
    const baseSalary = 40000; // 預設底薪

    // 3. 薪資結算邏輯 (移植自您的 App.jsx)
    let csv = "\uFEFF工號,姓名,1號...[略],健康度,總工時,加班費,預估總薪資\n";
    
    Object.keys(finalizedSchedule).forEach(staffId => {
      if (staffId.startsWith('D')) return; // 略過虛擬班次
      
      const staff = staffData.find(s => s.staff_id === staffId);
      const name = staff?.name || "未知";
      const schedule = finalizedSchedule[staffId];
      
      let workDays = 0, nightCount = 0;
      Object.values(schedule).forEach(cell => {
        const type = (typeof cell === 'object') ? cell.type : cell;
        if (['D', 'E', 'N', '支援'].includes(type)) workDays++;
        if (type === 'N') nightCount++;
      });

      // 簡易薪資計算示範 (可依需求細化)
      const dailyWage = Math.round(baseSalary / 30);
      const totalSalary = baseSalary + (nightCount * 500); // 假設夜班津貼 500

      csv += `${staffId},${name},...,90,${workDays},0,${totalSalary}\n`;
    });

    // 4. 上傳至 archive_reports 集合
    await db.collection('archive_reports').doc(docId).set({
      csv: csv,
      timestamp: admin.firestore.FieldValue.serverTimestamp(),
      autoGenerated: true
    });

    return res.status(200).json({ success: true, message: `${docId} 結算上傳成功！` });

  } catch (error) {
    console.error("❌ 自動結算失敗:", error);
    return res.status(500).json({ error: error.message });
  }
}