import admin from 'firebase-admin';

export default async function handler(req, res) {
  try {
    // 1. 初始化 Firebase Admin (保持原本的寫法)
    if (!admin.apps.length) {
      if (!process.env.FIREBASE_SERVICE_ACCOUNT) {
        return res.status(500).json({ error: "❌ 找不到環境變數 FIREBASE_SERVICE_ACCOUNT" });
      }
      let serviceAccount;
      try {
        serviceAccount = JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT);
      } catch (e) {
        return res.status(500).json({ error: "❌ JSON 格式解析失敗", details: e.message });
      }
      if (serviceAccount.private_key) {
         serviceAccount.private_key = serviceAccount.private_key.replace(/\\n/g, '\n');
      }
      admin.initializeApp({
        credential: admin.credential.cert(serviceAccount)
      });
    }
    
    const db = admin.firestore();

    // ==========================================
    // 🌟 Time Tuner (時光機模組) 🌟
    // ==========================================
    // 檢查網址有沒有帶參數，例如: ?force=true 或 ?targetDate=2026-02-28
    const isForceRun = req.query.force === 'true'; 
    const targetDateStr = req.query.targetDate;

    // 如果有給假時間，就用假時間；沒有的話就用真實的「今天」
    const today = targetDateStr ? new Date(targetDateStr) : new Date();
    
    // 計算明天是幾號
    const tomorrow = new Date(today);
    tomorrow.setDate(today.getDate() + 1);
    
    // 如果不是強制執行，且明天不是 1 號 (代表今天不是月底)，就乖乖跳過
    if (!isForceRun && tomorrow.getDate() !== 1) {
      return res.status(200).json({ message: '尚未到月底最後一天，跳過自動結算。' });
    }

    // 使用計算出的「當前時間」(可能是假時間) 來決定要結算哪個月
    const year = today.getFullYear();
    const month = today.getMonth() + 1;
    // ==========================================

    const scheduleDocId = `${year}-${month}`; // 尋找 Scheduls 裡的 2026-2
    const archiveDocId = `${year}_${month}`;  // 存入 archive_reports 裡的 2026_2

    // 3. 抓取資料庫
    const staffRef = db.collection('NurseApp').doc('Staff');
    const scheduleRef = db.collection('Schedules').doc(scheduleDocId);

    const [staffSnap, scheduleSnap] = await Promise.all([ staffRef.get(), scheduleRef.get() ]);

    if (!scheduleSnap.exists) {
        return res.status(404).json({ error: `❌ 找不到 ${year}年${month}月 的班表，無法結算！(尋找的文檔ID: ${scheduleDocId})` });
    }
    
    const staffData = staffSnap.data()?.staffData || [];
    const finalizedSchedule = scheduleSnap.data()?.finalizedSchedule || {};
    const baseSalary = 40000; 

    // 4. 產生 CSV 
    let csv = "\uFEFF工號,姓名,1號...[略],健康度,總工時,加班費,預估總薪資\n";
    
    Object.keys(finalizedSchedule).forEach(staffId => {
      if (staffId.startsWith('D')) return;
      const staff = staffData.find(s => s.staff_id === staffId);
      const name = staff?.name || "未知";
      const schedule = finalizedSchedule[staffId];
      
      let workDays = 0, nightCount = 0;
      Object.values(schedule).forEach(cell => {
        const type = (typeof cell === 'object') ? cell.type : cell;
        if (['D', 'E', 'N', '支援'].includes(type)) workDays++;
        if (type === 'N') nightCount++;
      });

      const totalSalary = baseSalary + (nightCount * 500); 
      csv += `${staffId},${name},...,90,${workDays},0,${totalSalary}\n`;
    });

    // 5. 上傳至歷史庫
    await db.collection('archive_reports').doc(archiveDocId).set({
      csv: csv,
      timestamp: admin.firestore.FieldValue.serverTimestamp(),
      autoGenerated: true
    });

    return res.status(200).json({ success: true, message: `✅ [TimeTuner: ${year}-${month}] 自動結算上傳成功！` });

  } catch (error) {
    console.error("❌ 伺服器崩潰:", error);
    return res.status(500).json({ error: "❌ 伺服器執行時發生錯誤", details: error.message });
  }
}